# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Billing  row house' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Billing  row house

  target 'Billing  row houseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Billing  row houseUITests' do
    # Pods for testing
  end

  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Alamofire'

end
