# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Billing Apartment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Billing Apartment
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'	

  target 'Billing ApartmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Billing ApartmentUITests' do
    # Pods for testing
  end

end
